AWSTemplateFormatVersion: 2010-09-09
Description: A cloudfront distribution stack
Parameters:
  PipelineID:
    Description: Existing Bucket Name
    Type: String
Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website.
  WebPageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !Sub ${PipelineID}.s3.amazonaws.com
            Id: webpage
            S3OriginConfig:
             OriginAccessIdentity: 
              Fn::Sub: origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: false

Outputs:
  PipelineID:
    Value: !Sub ${PipelineID}
    Export:
      Name: PipelineID
