AWSTemplateFormatVersion: 2010-09-09
Description: Creating infrastructure with ci job
Resources:
  EC2Instances:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: projansible
      ImageId: ami-0d70546e43a941d70
      InstanceType: t2.micro
      SecurityGroups: !Ref InstanceSecurityGroup
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: To enable SSH access via port 22
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
