# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: Create Cloud Formation Stack
          command: |
            aws cloudformation create-stack \
              --template-body file://template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-west-2

# Invoke jobs via workflows
workflows:
  say-hello-workflow:
    jobs:
      - create-infrastructure
